# -*- coding: utf-8 -*-
"""ExerciciosPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ndbx33fk_07BoczbudhubUUENZecPvjc

1 - Faça um programa para leitura de
três notas parciais de um aluno. O programa deve calcular a média alcançada por
aluno e apresentar:

a) A mensagem
"Aprovado", se a média for maior ou igual a 7, com a respectiva média
alcançada;

b) A mensagem
"Reprovado", se a média for menor do que 7, com a respectiva média
alcançada;

c) A mensagem "Aprovado com
Distinção", se a média for igual a 10.
"""

print("Calculadora de média de 3 notas - Machine")

print("Bem vindo ao calculador de média escolar")
print("Digite o valor de 0 a 10!")
print("A média para ser aprovado é de 7")


try:
  n1 = float(input("Digite a primeira nota: "))
  while (n1>10) or (n1<0):
    n1 = float(input("Valor invalido! Digite a primeira nota: "))

  n2 = float(input("Digite a segunda nota: "))
  while (n2>10) or (n2<0):
    n2 = float(input("Valor invalido! Digite a segunda nota: "))

  n3 = float(input("Digite a terceira nota: "))
  while (n3>10) or (n3<0):
    n3 = float(input("Valor invalido! Digite a terceira nota: "))


except:
  print("Opção Invalida! Digite um valor entre um 0 e 10!")

else:
  media = float(n1+n2+n3)/3 
  print("Sua Média foi: ")
  print(round(media, 1))


  if media > 10:
      print("Opção invalida!")


  elif media < 0:
      print("Opção invalida!")  


  if media == 10:
      print("Aluno Aprovado com Distinção")
        
  elif media >= 7:
      print("Aluno Aprovado")  

  else:
      print("Aluno Reprovado")

"""2- Faça um programa que peça uma
nota, entre zero e dez. Mostre uma mensagem caso o valor seja inválido e
continue pedindo até que o usuário informe um valor válido.
"""

print("Apenas números de 0 a 10 serão aceitos - Machine")

n = float(input("Digite uma nota de 0 a 10: "))

while (n>10) or (n<0):
  
  if n >= 11 or n < 0:
    print("Número inválido! Tente novamente!")
  
  n = float(input("Digite uma nota de 1 a 10: "))

"""3- Faça
um Programa que peça a temperatura em graus Fahrenheit, transforme e mostre a
temperatura em graus Celsius. C = 5 * ((F-32) / 9).

"""

print("Transformador de graus Fahrenheit em Celsius - Machine")

f = float(input("Digite a temperatura em Fahrenheit: "))
c = 5*((f-32)/9)

print("A temperatura de {}° Fahrenheit é igual a {}° Celsius". format(f, c))

"""3.1- Faça um Programa que peça a temperatura em graus Celsius, transforme e mostre a temperatura em graus Fahrenheit. F=((9*C)/5)+32."""

print("Transformador de graus Celsius em Fahrenheit - Machine")

c = float(input("Digite a temperatura em Celsius: "))
f = ((9*c)/5)+32

print("A temperatura de {}° Celsius é igual a {}° Fahrenheit". format(c, f))

"""4- Faça
um Programa que peça um número correspondente a um determinado ano e em seguida
informe se este ano é ou não bissexto.
"""

print("Descubra se o ano é Bissexto - Machine")

ano = int(input("Digite o ano para saber se ele é bissexto: "))
if ano % 4 == 0 and ano % 100 != 0 or ano % 400 == 0:
  print("O ano de {} é bissexto!".format(ano))
else:
  print("O ano de {} não é bissexto!".format(ano))

"""5 - Faça
um programa que gera uma lista dos números primos existentes entre 1 e um
número inteiro informado pelo usuário.

"""

print("Filtro de Números Primos - Machine")

n = int(input("Digite o número máximo de 1 a X, digite o valor de X: "))

lista = []
for i in range(n + 1):
    if i % 2 == 1 and i !=2 or i == 2:
      lista.append(i)
      
print(f"Números {lista}")

"""6 - Faça
um Programa que peça a idade e a altura de 5 pessoas, armazene cada informação
no seu respectivo vetor. Imprima a idade e a altura na ordem inversa a ordem
lida.

"""

print("Lista inversa de idade e altura de 5 pessoas - Machine")

lista = []
for n_pessoas in range (1,6):
    
    idade = int(input("Idade: "))
    lista.append(idade)

    altura = float(input("Altura: "))
    lista.append(altura)

lista.reverse()
print(lista)

"""7- Reverso
do número. Faça uma função que retorne o reverso de um número inteiro
informado.
"""

print("Digite um número qualquer e receba ele invertido - Machine")

n = int(input("O número digitado é: "))

n = str(n)

print(n[::-1])